IF EXISTS (SELECT 1 FROM Sys.procedures WHERE name = 'MURSPCOPIAPRECIOSVTAS')
DROP PROCEDURE dbo.MURSPCOPIAPRECIOSVTAS
GO
CREATE PROC MURSPCOPIAPRECIOSVTAS
@Id                         Int,
@Mov				        Varchar(50),
@Estatus			        Varchar(50),
--@ACTUALIZADO                Bit,
@OrigenTipo                 Varchar(10)
AS BEGIN


--se cambian a variables de entrada
--SELECT @MOV  = MOV,@ESTATUS=ESTATUS,@ORIGENTIPO=ORIGENTIPO FROM VENTA WHERE ID=@ID


IF @OrigenTipo IS NULL

BEGIN
UPDATE VENTAD
SET LISTAACTUALIZONVTK=0
WHERE ID=@ID

END




IF @MOV='COTIZACION' AND @ESTATUS='SINAFECTAR'
BEGIN


UPDATE VENTAD
SET LISTAPRECIONVTK=ISNULL(T.PrecioLista,0),
 LISTAPRECIO2NVTK=ISNULL(T.PRECIO2,0),
 LISTAPRECIO3NVTK=ISNULL(T.PRECIO3,0),
 LISTAPRECIO4NVTK=ISNULL(T.PRECIO4,0),
 LISTAPRECIO5NVTK=ISNULL(T.PRECIO5,0),
 LISTAPRECIO6NVTK=ISNULL(T.Precio6,0),
 LISTAPRECIO7NVTK=ISNULL(T.PRECIO7,0),
 LISTAPRECIO8NVTK=ISNULL(T.Precio8,0),
 LISTAPRECIO9NVTK=ISNULL(T.Precio9,0),
 LISTAPRECIO10NVTK=ISNULL(T.Precio10,0),
 LISTAPRECIOMINIMONVTK=ISNULL(T.PrecioMinimo,0),
 LISTAACTUALIZONVTK=1

FROM VENTAD V , ART  T  
WHERE V.ID=@ID  AND V.ARTICULO=T.Articulo
AND ISNULL( LISTAACTUALIZONVTK,0)<>1


END



IF @MOV IN( SELECT MOV FROM  MOVTIPO WHERE MODULO='VTAS' AND SubClave ='VTAS.PNVK' AND MOV <>'COTIZACION')
AND @ESTATUS='SINAFECTAR'
BEGIN


UPDATE VENTAD
SET LISTAPRECIONVTK=ISNULL(T.PrecioLista,0),
 LISTAPRECIO2NVTK=ISNULL(T.PRECIO2,0),
 LISTAPRECIO3NVTK=ISNULL(T.PRECIO3,0),
 LISTAPRECIO4NVTK=ISNULL(T.PRECIO4,0),
 LISTAPRECIO5NVTK=ISNULL(T.PRECIO5,0),
 LISTAPRECIO6NVTK=ISNULL(T.Precio6,0),
 LISTAPRECIO7NVTK=ISNULL(T.PRECIO7,0),
 LISTAPRECIO8NVTK=ISNULL(T.Precio8,0),
 LISTAPRECIO9NVTK=ISNULL(T.Precio9,0),
 LISTAPRECIO10NVTK=ISNULL(T.Precio10,0),
 LISTAPRECIOMINIMONVTK=ISNULL(T.PrecioMinimo,0),
 LISTAACTUALIZONVTK=1

FROM VENTAD V , ART  T  
WHERE V.ID=@ID  AND V.ARTICULO=T.Articulo
AND ISNULL( LISTAACTUALIZONVTK,0)<>1


END



RETURN
END