IF EXISTS (SELECT 1 FROM Sys.procedures WHERE name = 'MURSPAVISAPARTIDASDESCUENTO')
DROP PROCEDURE dbo.MURSPAVISAPARTIDASDESCUENTO
GO
CREATE PROC MURSPAVISAPARTIDASDESCUENTO

@ID  INT,
@OK  INT OUTPUT,
@OKREF VARCHAR(255) OUTPUT

AS BEGIN
 IF EXISTS (SELECT * FROM VentaD WHERE ID=@ID AND DescripcionExtra LIKE '%DEBAJO%')
 BEGIN
 SELECT @OK=20310, @OKREF='HAY ARTICULOS CON PRECIO POR DEBAJO DEL DESCUENTO PERMITIDO'
 END
 END